Repository endless-sky/endless-sky-wiki, pull requests merged in 2024-11, with the labels that each got.

#71 fix(bug): update the description of `"cloak by mass"` to work correctly
  wiki/CreatingOutfits.md
Labels: standalone

#55 Fix and clarify `disabled recovery` properties in CreatingOutfits.md
  wiki/CreatingOutfits.md
Labels: documentation, standalone

#64 fix: Add missing ring/bar interface properties
  wiki/CreatingInterfaces.md
Labels: documentation, standalone

#61 Wiki for 10580 (removing log entries)
  wiki/CreatingMissions.md
Labels: enhancement

#76 Wiki for new jump fuel attributes (10732)
  wiki/CreatingOutfits.md
Labels: enhancement

#73 Object visibility docs
  wiki/MapData.md
Labels: enhancement
