Repository endless-sky/endless-sky-wiki, pull requests merged in 2024-10, with the labels that each got.

#53 Remove erroneous word
  wiki/CreatingNews.md
Labels: documentation, standalone

#68 fix: Missing documentation for interface `list` elements
  wiki/CreatingInterfaces.md
Labels: documentation, standalone

#62 Silent scans and jumps
  wiki/CreatingOutfits.md
Labels: enhancement

#60 Feature: cloaked shield permeability
  wiki/CreatingOutfits.md
Labels: enhancement

#70 Feature: Documentation for #10710
  wiki/ShipPersonalities.md
Labels: enhancement

#1 Some weapon property clarifications
  wiki/CreatingOutfits.md
Labels: documentation, standalone

#65 fix: Correct raid prevention attribute name
  wiki/MapData.md
Labels: bug, standalone
