Repository endless-sky/endless-sky-wiki, pull requests merged in 2025-03, with the labels that each got.

#93 Update StyleGoals.md with info on writing and grammar
  .codespell.exclude
  wiki/StyleGoals.md
Labels: documentation, standalone

#96 Clarify that the sprite path of a stellar object has a meaning
  wiki/MapData.md
Labels: standalone

#103 Outfit series update for #10629
  wiki/CreatingOutfits.md
Labels: documentation

#112 Documentation for turret turn multipliers
  wiki/CreatingOutfits.md
  wiki/CreatingShips.md
Labels: enhancement

#109 Typo fix: your -> their in HumanSpace.md
  wiki/HumanSpace.md
Labels: typo, standalone

#101 Document multiline `about`s
  wiki/CreatingPlugins.md
Labels: documentation, standalone

#35 Wiki update for 10368 (wrapped text elements)
  wiki/CreatingInterfaces.md
Labels: enhancement

#110 Gradient Interface Colors
  wiki/CreatingInterfaces.md
Labels: enhancement

#116 fix(typo): `takeoff`, not `take off`
  wiki/Player-Conditions.md
Labels: typo

#114 Include different date formats in mission deadline substitution descriptions
  wiki/CreatingMissions.md
Labels: standalone

#113 feat(news): Use global and player substitutions in news messages
  wiki/CreatingNews.md
Labels: enhancement

#13 Added pause default key binding
  wiki/PlayersManual.md
Labels: enhancement

#98 Wiki for out-of-ammo sounds (10693)
  wiki/CreatingOutfits.md
Labels: enhancement

#111 Add avgi to tier list
  wiki/StoryIdeas.md
Labels: documentation, standalone

#84 Mission offer precedence documentation
  wiki/CreatingMissions.md
Labels: enhancement

#121 Typo fix: Swapping "abc" and "xyz" in "Writing Conversations"
  wiki/WritingConversations.md
Labels: standalone
