Repository endless-sky/endless-sky-wiki, pull requests merged in 2025-05, with the labels that each got.

#139 Add docs on opengl shaders
  wiki/CreatingPlugins.md
Labels: enhancement, standalone

#52 Wiki update for 10508 (turret blindspots)
  wiki/CreatingShips.md
Labels: enhancement

#33 ES PR: NPC Travel Instructions (#8621)
  wiki/CreatingMissions.md
Labels: enhancement

#149 fix(content): correct version information
  wiki/CreatingMissions.md
Labels: standalone

#143 "in flight" mission location
  wiki/CreatingMissions.md
Labels: enhancement
