Repository endless-sky/endless-sky-wiki, pull requests merged in 2025-09, with the labels that each got.

#169 Combat strength conditions
  wiki/Player-Conditions.md
Labels: enhancement

#41 Wiki PR for AVIF support (10391)
  wiki/SpriteData.md
Labels: enhancement

#172 Fix hardpoint swizzle formatting
  wiki/CreatingOutfits.md
Labels: bug

#119 add information about gaslining
  wiki/CreatingOutfits.md
  wiki/CreatingShips.md
Labels: standalone

#81 Document to spawn for fleets and hazards
  wiki/CreatingEvents.md
  wiki/MapData.md
Labels: enhancement
