Repository endless-sky/endless-sky-wiki, pull requests merged in 2025-02, with the labels that each got.

#87 Replace "apply" with "action"
  wiki/CreatingMissions.md
Labels: documentation, standalone

#92 Better explain the meaning of zero missile strength
  wiki/CreatingOutfits.md
Labels: standalone

#95 Creating a new Reviewing PRs wiki page
  wiki/ReviewingPRs.md
  wiki/_Sidebar.md
Labels: standalone

#69 Wiki for 10655 (live effects on minables)
  wiki/CreatingMinables.md
Labels: enhancement

#99 Missing version info
  wiki/CreatingEffects.md
Labels: documentation, standalone

#100 Add ReviewingPRs to Home.md
  wiki/Home.md
Labels: documentation, standalone
