Repository endless-sky/endless-sky-wiki, pull requests merged in 2025-07, with the labels that each got.

#126 wiki(mechanics): Allow for more granular control of homing attributes
  wiki/CreatingOutfits.md
Labels: enhancement

#160 Hardpoint parent swizzle
  wiki/CreatingOutfits.md
Labels: enhancement

#157 Copyright files aren't required for plugins
  wiki/CreatingPlugins.md
Labels: standalone

#156 Fix inline code style
  wiki/MapData.md
Labels: typo, standalone
